### ISSUE TITLE
Compiling on debian sid, cannot find libraries

### ISSUE THREAD

**Issue by j-mir-prazak** [paperManu/splash#63] opened 2018-12-21 19:09 UTC
I don't seem to be able to compile on debian. i get to the 91%, but then ld cannot find libraries:
[ 91%] Linking CXX executable splash
/usr/bin/ld: cannot find -lgme
/usr/bin/ld: cannot find -lopenmpt
/usr/bin/ld: cannot find -lchromaprint
/usr/bin/ld: cannot find -lbluray
/usr/bin/ld: cannot find -lgcrypt
/usr/bin/ld: cannot find -lgnutls
/usr/bin/ld: cannot find -lvpx
/usr/bin/ld: cannot find -lwebpmux
/usr/bin/ld: cannot find -lwebp
/usr/bin/ld: cannot find -lcrystalhd
/usr/bin/ld: cannot find -lopencore-amrwb
/usr/bin/ld: cannot find -lzvbi
/usr/bin/ld: cannot find -laom
/usr/bin/ld: cannot find -lcodec2
/usr/bin/ld: cannot find -lfdk-aac
/usr/bin/ld: cannot find -lilbc
/usr/bin/ld: cannot find -lopencore-amrnb
/usr/bin/ld: cannot find -lopus
/usr/bin/ld: cannot find -lshine
/usr/bin/ld: cannot find -ltheoraenc
/usr/bin/ld: cannot find -ltheoradec
/usr/bin/ld: cannot find -lvo-amrwbenc
/usr/bin/ld: cannot find -lx264
/usr/bin/ld: cannot find -lx265
/usr/bin/ld: cannot find -lxvidcore
/usr/bin/ld: cannot find -lopenh264
/usr/bin/ld: cannot find -lkvazaar
/usr/bin/ld: cannot find -lva
/usr/bin/ld: cannot find -lmfx
/usr/bin/ld: cannot find -lva-drm
/usr/bin/ld: cannot find -lva-x11
/usr/bin/ld: cannot find -lsoxr
/usr/bin/ld: cannot find -lvdpau
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/splash.dir/build.make:95: src/splash] Error 1
make[1]: *** [CMakeFiles/Makefile2:444: src/CMakeFiles/splash.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by paperManu** [comment] 2018-12-29 02:37
Hi j-mir-prazak,
By any chance, did you try compile it against the system libraries, as explained [here](https://github.com/paperManu/splash#building) ?
It looks like an issue with FFmpeg when built using the `make_deps.sh` script, I'll investigate this.

Thanks for your interest in Splash ! ;)

**Comment by j-mir-prazak** [comment] 2018-12-29 09:34
hi,
yeah, in the end i managed to compile against system libraries, though i had to track down few Sid doesn't have in repositories. i hoped that the thing will be more stable, but it crashes without much of a error why, though it seems to be just some simple glitch where i click on something before something else a it just cannot handle it. but where much can be just my drivers or gnome doing it - i will try to find out what exactly causes it. it does it also with the precompiled version. will try flatpack if also crashes.

thanks!

**Comment by paperManu** [comment] 2018-12-29 14:18
Could you copy the output of `glxinfo` ?

Also, if you have the chance, could you run Splash inside gdb and give me the full backtrace:
```bash
gdb splash
run
# Wait until it crashes, then:
bt full
```

**Comment by paperManu** [comment] 2018-12-29 14:20
BTW, I tried building it inside docker with a `debian:sid` image and had no issue regarding linking against FFmpeg dependencies.

**Comment by sphaero** [comment] 2019-01-23 14:25
I see similar problems in #66.

using Debian Buster

```
git clone https://gitlab.com/sat-metalab/splash
cd splash/
git submodule update --init
mkdir -p build && cd build
cmake -DUSE_SYSTEM_LIBS=ON ..
make
```

**Comment by paperManu** [comment] 2019-03-11 20:06
I tested it again with the latest develop branch, on Debian Sid and Debian Buster, and I could not reproduce this issue. I'll close it for now, please reopen it with some way to reproduce it on a clean system (ideally in a docker container) if it still happens

**Closed by paperManu** 2019-03-11 20:06 UTC
Labels: bug
