### ISSUE TITLE
Inconsistent mesh loading when texture file not loaded

### ISSUE THREAD

**Issue by charlesveasey** [paperManu/splash#47] opened 2018-02-02 15:51 UTC
Splash Version 0.7.13
Branch: develop
OS: lubuntu 16.04 Alternate 64-bit

The mesh is inconsistently loading on startup. It seems to be caused by a bad `Image` filename in the JSON config file. This is true even if the `Image` block is set to: `"type" : "image_v4l2"`. It is a bit confusing as Splash saves the config file without a filename when set to `"type" : "image_v4l2"` in the GUI.  I have to add a placeholder filename in JSON, or reload the mesh during runtime. 

      "Image" : {
         "autosetResolution" : [ 1 ],
         "captureSize" : [ 1920, 1080 ],
         "device" : [ "/dev/video0" ],
         "doCapture" : [ 1 ],
         "file" : [ "" ],
         "flip" : [ 0 ],
         "flop" : [ 0 ],
         "index" : [ 0 ],
         "pattern" : [ 0 ],
         "pixelFormat" : [ "RGB" ],
         "priorityShift" : [ 0 ],
         "sourceFormat" : [ "" ],
         "srgb" : [ 1 ],
         "type" : "image_v4l2"
      },

**Comment by paperManu** [comment] 2018-02-02 16:10
Could you give me the whole configuration (JSON + obj file + image) which shows this issue?

**Comment by charlesveasey** [comment] 2018-02-02 17:49
If you remove the image filename in any JSON file, then the _default_ mesh will be loaded on startup, not the one listed in the JSON.

`"image" : {"type" : "image", "file" : "", "benchmark" : 0, "srgb" : 1},`

A little more difficult to reproduce:
1. Export a configuration in Blender with an image file.
2. Load with Splash (everything ok).
3. Use the Splash GUI to save the media type as Video4Linux (the image filename will be removed in the JSON).
4. Reload the config file (results in the inconsistency).

The JSON seems to be at fault. I can take the template "single_dome.json" reproduce steps 3 and 4 and it still works. 

If I export the JSON file in Blender, then I have to add a placeholder image filename in JSON in order for everything to work correctly on startup after steps 3 and 4.

I've included the three files you requested:
[splash-issue-47.tar.gz](https://github.com/paperManu/splash/files/1690270/splash-issue-47.tar.gz)

**Comment by paperManu** [comment] 2018-02-02 19:43
Hey Charles,
It looks like you managed to reproduce a bug I have been trying to get rid of for some time, but I was unable to reproduce it with a simple configuration.
It should be fixed, could you please check the bug/load_race_condition branch?

**Comment by charlesveasey** [comment] 2018-02-02 20:28
I can't find the branch. Did you push it?

**Comment by paperManu** [comment] 2018-02-02 20:34
Sorry, I did not push it on the correct repo. You should be able to get it now.

**Comment by charlesveasey** [comment] 2018-02-02 21:00
Yes. It's fixed on that branch. Thanks!

**Comment by paperManu** [comment] 2018-02-02 21:23
Good. I'll merge it in develop then.

**Closed by paperManu** 2018-02-02 21:23 UTC
